version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockhoolm
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - HOMEBRIDGE_DEBUG=1
    volumes:
      - ./homebridge:/homebridge
      - ./:/node_modules/homebridge-yr/
    ports:
      - 8080:8080
      - 53082:53082